# Generated by Django 5.2.8 on 2025-11-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_images_imag_created_33c7eb_idx_images_imag_created_d57897_idx'),
    ]

    operations = [
    ]
