# Generated by Django 5.2.8 on 2025-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_imagemodel_to_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
