# Generated by Django 5.2.8 on 2025-11-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
