# Generated by Django 5.2.8 on 2025-11-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_alter_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="original_image",
        ),
        migrations.AddField(
            model_name="image",
            name="edited_image",
            field=models.ImageField(blank=True, upload_to="images/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="image",
            name="prompt",
            field=models.TextField(blank=True),
        ),
    ]
