# Generated by Django 5.2.8 on 2025-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_image_image_edited_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
